# -*- coding: utf-8 -*-
"""Assignment 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aomg6NBO1Ee494Pdbje7pC2vcpd3rneN

**Registration and Login system using Python, file handling**
"""

import re
def register():
  with open('username.txt', mode = 'a') as user_file:
    username = input("Enter Username : ")
    regex = re.compile(r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2}\b')
    if username == regex.fullmatch(username):
      user_file.write(f"{username}\n")
    else:
      print("your email is not valid")

    with open('password.txt', mode = 'a')as pass_file:
      password = input("Enter Password: ")
      pattern = re.compile(r'[a-zA-Z0-9@#|$%^&*]{6,}')
      if password ==pattern.fullmatch(password):
        pass_file.write(f"{password}\n")
      else:
        print("your password should be atleast 6 characters long")

register()